name: A Composite Action
description: 'Greet someone and record the time'
outputs:
  STEP_OUTPUT:
    description: dump inputs
    value: ${{ toJson(inputs) }}
runs:
  using: composite
  steps:
  - id: step1
    run: env
    shell: bash
    env:
      INTERNAL_ABC: xyz
      INTERNAL_COE: ${{ inputs.coe }}
      INTERNAL_FOOBAR: ${{ inputs.foobar }}
      INTERNAL_STEP_INPUTS: ${{ toJson(inputs) }}
  - id: step2
    uses: actions/github-script@v7
    with:
      script: return "Hello!"
      result-encoding: string
  - id: step3
    uses: ./.github/actions/composite2