name: Demo

on:
  push:
  workflow_dispatch:

env:
  FOO: bar

jobs:
  job-run-on-vm:
    runs-on: self-hosted
    env:
      FOOBAR: foobar-env
    steps:
      - name: command message
        run: |
          echo "::debug::Set the Octocat variable"
          echo "::notice file=.github/workflows/demo.yml,line=1,col=5,endColumn=7::The notice message"
          echo "::warning file=.github/workflows/demo.yml,line=2,col=5,endColumn=7,title=WARNING TITLE::The warning message"
          echo "::error file=.github/workflows/demo.yml,line=3,col=5,endColumn=7,title=ERROR TITLE::The error message"

      - name: env
        run: env | sort

      # - name: Dump GitHub context
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |          
          echo "$GITHUB_CONTEXT"
          echo "Hello world"

      - name: Generate list using Markdown
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate 10M log
        run: |
          go run main.go 10

      - name: Generate 100M log
        run: |
          go run main.go 100
