on:
  push:
  workflow_dispatch:

jobs:
  parallel-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
    
      - parallel:
          - name: ping
            run: |
              for i in {1..30}; do
                ping -c 1 google.com
                sleep 1
              done
    
          - name: echo
            run: |
              for i in {1..10}; do
                echo "hello world"
                sleep 2
              done
    
          - name: count
            run: |
              for i in {1..30}; do
                echo "$i"
                sleep 0.5
              done
    
      - name: Last
        run: Echo "all done"
